-- MySQL Script generated by MySQL Workbench
-- Sat 16 Dec 2017 22:07:26 AEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema altershift
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `altershift` ;

-- -----------------------------------------------------
-- Schema altershift
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `altershift` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema timegrid
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `timegrid` ;

-- -----------------------------------------------------
-- Schema timegrid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `timegrid` DEFAULT CHARACTER SET latin1 ;
USE `altershift` ;

-- -----------------------------------------------------
-- Table `altershift`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altershift`.`users` ;

CREATE TABLE IF NOT EXISTS `altershift`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `is_staff` TINYINT(1) NOT NULL DEFAULT 0,
  `profile_pic` VARCHAR(150) NULL,
  `bio` VARCHAR(900) NULL DEFAULT NULL,
  `initial_consult` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `altershift`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altershift`.`services` ;

CREATE TABLE IF NOT EXISTS `altershift`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `users_id` INT NOT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_services_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_services_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `altershift`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `altershift`.`services_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altershift`.`services_detail` ;

CREATE TABLE IF NOT EXISTS `altershift`.`services_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` INT NULL,
  `price` INT NULL,
  `break` INT NULL DEFAULT 0,
  `initial_consult` TINYINT(1) NULL DEFAULT 0,
  `services_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_services_detail_services1_idx` (`services_id` ASC),
  CONSTRAINT `fk_services_detail_services1`
    FOREIGN KEY (`services_id`)
    REFERENCES `altershift`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `altershift`.`availability`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altershift`.`availability` ;

CREATE TABLE IF NOT EXISTS `altershift`.`availability` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start` TIME NULL,
  `end` TIME NULL,
  `repeat_weekday` INT NULL,
  `services_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_availability_services1_idx` (`services_id` ASC),
  INDEX `fk_availability_services2_idx` (`users_id` ASC),
  CONSTRAINT `fk_availability_services1`
    FOREIGN KEY (`services_id`)
    REFERENCES `altershift`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_availability_services2`
    FOREIGN KEY (`users_id`)
    REFERENCES `altershift`.`services` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `altershift`.`bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altershift`.`bookings` ;

CREATE TABLE IF NOT EXISTS `altershift`.`bookings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start` TIMESTAMP NOT NULL,
  `finish` TIMESTAMP NULL,
  `status` ENUM('R', 'C', 'A', 'S') NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `users_id` INT NOT NULL,
  `services_id` INT NOT NULL,
  `services_detail_id` INT NOT NULL,
  `is_recurring` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Bookings_users1_idx` (`users_id` ASC),
  INDEX `fk_Bookings_services1_idx` (`services_id` ASC),
  INDEX `fk_Bookings_services_detail1_idx` (`services_detail_id` ASC),
  CONSTRAINT `fk_Bookings_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `altershift`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bookings_services1`
    FOREIGN KEY (`services_id`)
    REFERENCES `altershift`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bookings_services_detail1`
    FOREIGN KEY (`services_detail_id`)
    REFERENCES `altershift`.`services_detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `altershift`.`recurring_bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altershift`.`recurring_bookings` ;

CREATE TABLE IF NOT EXISTS `altershift`.`recurring_bookings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` INT NULL,
  `day_of_week` INT NULL,
  `day_of_month` INT NULL,
  `bookings_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `start` TIME NULL,
  `end` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recurring_bookings_bookings1_idx` (`bookings_id` ASC),
  CONSTRAINT `fk_recurring_bookings_bookings1`
    FOREIGN KEY (`bookings_id`)
    REFERENCES `altershift`.`bookings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `timegrid` ;

-- -----------------------------------------------------
-- Table `timegrid`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`categories` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`categories` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `strategy` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL DEFAULT 'dateslot',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `categories_slug_unique` (`slug` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`users` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(60) CHARACTER SET 'utf8' NOT NULL,
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `last_login_at` TIMESTAMP NULL DEFAULT NULL,
  `last_ip` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_username_unique` (`username` ASC),
  UNIQUE INDEX `users_email_unique` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`domains`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`domains` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`domains` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `owner_id` INT(10) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `domains_slug_unique` (`slug` ASC),
  INDEX `domains_owner_id_foreign` (`owner_id` ASC),
  CONSTRAINT `domains_owner_id_foreign`
    FOREIGN KEY (`owner_id`)
    REFERENCES `timegrid`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`businesses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`businesses` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`businesses` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` INT(10) UNSIGNED NOT NULL,
  `domain_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `slug` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `postal_address` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `phone` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `social_facebook` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `timezone` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `strategy` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL DEFAULT 'timeslot',
  `plan` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `country_code` VARCHAR(2) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `locale` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `listed` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `businesses_slug_unique` (`slug` ASC),
  INDEX `businesses_category_id_foreign` (`category_id` ASC),
  INDEX `businesses_country_code_index` (`country_code` ASC),
  INDEX `businesses_domain_id_foreign` (`domain_id` ASC),
  CONSTRAINT `businesses_category_id_foreign`
    FOREIGN KEY (`category_id`)
    REFERENCES `timegrid`.`categories` (`id`),
  CONSTRAINT `businesses_domain_id_foreign`
    FOREIGN KEY (`domain_id`)
    REFERENCES `timegrid`.`domains` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`contacts` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`contacts` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `nin` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `gender` ENUM('M', 'F') CHARACTER SET 'utf8' NOT NULL,
  `firstname` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `lastname` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `occupation` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `martial_status` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `postal_address` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `birthdate` DATE NULL DEFAULT NULL,
  `mobile` CHAR(15) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `mobile_country` CHAR(2) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `contacts_user_id_foreign` (`user_id` ASC),
  INDEX `contacts_nin_index` (`nin` ASC),
  CONSTRAINT `contacts_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `timegrid`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`humanresources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`humanresources` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`humanresources` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `slug` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `capacity` INT(10) UNSIGNED NOT NULL DEFAULT '1',
  `contact_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `business_id` INT(10) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `calendar_link` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `humanresources_contact_id_foreign` (`contact_id` ASC),
  INDEX `humanresources_business_id_foreign` (`business_id` ASC),
  INDEX `humanresources_slug_index` (`slug` ASC),
  CONSTRAINT `humanresources_business_id_foreign`
    FOREIGN KEY (`business_id`)
    REFERENCES `timegrid`.`businesses` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `humanresources_contact_id_foreign`
    FOREIGN KEY (`contact_id`)
    REFERENCES `timegrid`.`contacts` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`service_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`service_types` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`service_types` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `business_id` INT(10) UNSIGNED NOT NULL,
  `slug` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `service_types_business_id_foreign` (`business_id` ASC),
  INDEX `service_types_slug_index` (`slug` ASC),
  CONSTRAINT `service_types_business_id_foreign`
    FOREIGN KEY (`business_id`)
    REFERENCES `timegrid`.`businesses` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`services` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`services` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `business_id` INT(10) UNSIGNED NOT NULL,
  `slug` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `duration` INT(10) UNSIGNED NOT NULL DEFAULT '60',
  `description` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `prerequisites` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `color` VARCHAR(12) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `services_business_id_slug_unique` (`business_id` ASC, `slug` ASC),
  INDEX `services_type_id_foreign` (`type_id` ASC),
  CONSTRAINT `services_business_id_foreign`
    FOREIGN KEY (`business_id`)
    REFERENCES `timegrid`.`businesses` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `services_type_id_foreign`
    FOREIGN KEY (`type_id`)
    REFERENCES `timegrid`.`service_types` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`vacancies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`vacancies` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`vacancies` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `start_at` TIMESTAMP NULL DEFAULT NULL,
  `finish_at` TIMESTAMP NULL DEFAULT NULL,
  `business_id` INT(10) UNSIGNED NOT NULL,
  `service_id` INT(10) UNSIGNED NOT NULL,
  `capacity` INT(10) UNSIGNED NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `humanresource_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `vacancies_business_id_foreign` (`business_id` ASC),
  INDEX `vacancies_service_id_foreign` (`service_id` ASC),
  INDEX `vacancies_start_at_index` (`start_at` ASC),
  INDEX `vacancies_finish_at_index` (`finish_at` ASC),
  INDEX `vacancies_humanresource_id_foreign` (`humanresource_id` ASC),
  CONSTRAINT `vacancies_business_id_foreign`
    FOREIGN KEY (`business_id`)
    REFERENCES `timegrid`.`businesses` (`id`),
  CONSTRAINT `vacancies_humanresource_id_foreign`
    FOREIGN KEY (`humanresource_id`)
    REFERENCES `timegrid`.`humanresources` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `vacancies_service_id_foreign`
    FOREIGN KEY (`service_id`)
    REFERENCES `timegrid`.`services` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`appointments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`appointments` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`appointments` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `issuer_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `contact_id` INT(10) UNSIGNED NOT NULL,
  `business_id` INT(10) UNSIGNED NOT NULL,
  `hash` VARCHAR(32) CHARACTER SET 'utf8' NOT NULL,
  `status` ENUM('R', 'C', 'A', 'S') CHARACTER SET 'utf8' NOT NULL,
  `start_at` TIMESTAMP NULL DEFAULT NULL,
  `finish_at` TIMESTAMP NULL DEFAULT NULL,
  `duration` INT(11) NULL DEFAULT NULL,
  `service_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `comments` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `vacancy_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `humanresource_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `appointments_hash_unique` (`hash` ASC),
  INDEX `appointments_issuer_id_foreign` (`issuer_id` ASC),
  INDEX `appointments_contact_id_foreign` (`contact_id` ASC),
  INDEX `appointments_business_id_foreign` (`business_id` ASC),
  INDEX `appointments_service_id_foreign` (`service_id` ASC),
  INDEX `appointments_start_at_index` (`start_at` ASC),
  INDEX `appointments_finish_at_index` (`finish_at` ASC),
  INDEX `appointments_vacancy_id_foreign` (`vacancy_id` ASC),
  INDEX `appointments_humanresource_id_foreign` (`humanresource_id` ASC),
  CONSTRAINT `appointments_business_id_foreign`
    FOREIGN KEY (`business_id`)
    REFERENCES `timegrid`.`businesses` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `appointments_contact_id_foreign`
    FOREIGN KEY (`contact_id`)
    REFERENCES `timegrid`.`contacts` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `appointments_humanresource_id_foreign`
    FOREIGN KEY (`humanresource_id`)
    REFERENCES `timegrid`.`humanresources` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `appointments_issuer_id_foreign`
    FOREIGN KEY (`issuer_id`)
    REFERENCES `timegrid`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `appointments_service_id_foreign`
    FOREIGN KEY (`service_id`)
    REFERENCES `timegrid`.`services` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `appointments_vacancy_id_foreign`
    FOREIGN KEY (`vacancy_id`)
    REFERENCES `timegrid`.`vacancies` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`business_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`business_contact` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`business_contact` (
  `business_id` INT(10) UNSIGNED NOT NULL,
  `contact_id` INT(10) UNSIGNED NOT NULL,
  `notes` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  UNIQUE INDEX `business_contact_business_id_contact_id_unique` (`business_id` ASC, `contact_id` ASC),
  INDEX `business_contact_business_id_index` (`business_id` ASC),
  INDEX `business_contact_contact_id_index` (`contact_id` ASC),
  CONSTRAINT `business_contact_business_id_foreign`
    FOREIGN KEY (`business_id`)
    REFERENCES `timegrid`.`businesses` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `business_contact_contact_id_foreign`
    FOREIGN KEY (`contact_id`)
    REFERENCES `timegrid`.`contacts` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`business_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`business_user` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`business_user` (
  `business_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `business_user_business_id_index` (`business_id` ASC),
  INDEX `business_user_user_id_index` (`user_id` ASC),
  CONSTRAINT `business_user_business_id_foreign`
    FOREIGN KEY (`business_id`)
    REFERENCES `timegrid`.`businesses` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `business_user_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `timegrid`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`countries` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`countries` (
  `id` INT(11) NOT NULL,
  `capital` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `citizenship` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `country_code` CHAR(3) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `currency` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `currency_code` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `currency_sub_unit` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `currency_symbol` VARCHAR(3) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `full_name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `iso_3166_2` CHAR(2) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `iso_3166_3` CHAR(3) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `region_code` CHAR(3) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `sub_region_code` CHAR(3) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `eea` TINYINT(1) NOT NULL DEFAULT '0',
  `calling_code` VARCHAR(3) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `flag` VARCHAR(6) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `countries_id_index` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`migrations` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`notification_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`notification_categories` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`notification_categories` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `text` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `notification_categories_name_unique` (`name` ASC),
  INDEX `notification_categories_name_index` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`notification_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`notification_groups` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`notification_groups` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `notification_groups_name_unique` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`notifications` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`notifications` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `from_id` BIGINT(20) UNSIGNED NOT NULL,
  `from_type` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `to_id` BIGINT(20) UNSIGNED NOT NULL,
  `to_type` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `category_id` INT(10) UNSIGNED NOT NULL,
  `url` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `extra` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `read` TINYINT(4) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `expire_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `notifications_from_id_index` (`from_id` ASC),
  INDEX `notifications_from_type_index` (`from_type` ASC),
  INDEX `notifications_to_id_index` (`to_id` ASC),
  INDEX `notifications_to_type_index` (`to_type` ASC),
  INDEX `notifications_category_id_index` (`category_id` ASC),
  CONSTRAINT `notifications_category_id_foreign`
    FOREIGN KEY (`category_id`)
    REFERENCES `timegrid`.`notification_categories` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`notifications_categories_in_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`notifications_categories_in_groups` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`notifications_categories_in_groups` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` INT(10) UNSIGNED NOT NULL,
  `group_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `notifications_categories_in_groups_category_id_index` (`category_id` ASC),
  INDEX `notifications_categories_in_groups_group_id_index` (`group_id` ASC),
  CONSTRAINT `notifications_categories_in_groups_category_id_foreign`
    FOREIGN KEY (`category_id`)
    REFERENCES `timegrid`.`notification_categories` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `notifications_categories_in_groups_group_id_foreign`
    FOREIGN KEY (`group_id`)
    REFERENCES `timegrid`.`notification_groups` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`password_resets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`password_resets` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`password_resets` (
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `password_resets_email_index` (`email` ASC),
  INDEX `password_resets_token_index` (`token` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`permissions` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`permissions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `inherit_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `slug` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `permissions_inherit_id_index` (`inherit_id` ASC),
  INDEX `permissions_name_index` (`name` ASC),
  INDEX `permissions_slug_index` (`slug` ASC),
  CONSTRAINT `permissions_inherit_id_foreign`
    FOREIGN KEY (`inherit_id`)
    REFERENCES `timegrid`.`permissions` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`roles` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`roles` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `slug` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `roles_name_unique` (`name` ASC),
  UNIQUE INDEX `roles_slug_unique` (`slug` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`permission_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`permission_role` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`permission_role` (
  `permission_id` INT(10) UNSIGNED NOT NULL,
  `role_id` INT(10) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`permission_id`, `role_id`),
  INDEX `permission_role_role_id_foreign` (`role_id` ASC),
  CONSTRAINT `permission_role_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `timegrid`.`permissions` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `permission_role_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `timegrid`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`permission_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`permission_user` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`permission_user` (
  `permission_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`permission_id`, `user_id`),
  INDEX `permission_user_user_id_foreign` (`user_id` ASC),
  CONSTRAINT `permission_user_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `timegrid`.`permissions` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `permission_user_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `timegrid`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`preferences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`preferences` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`preferences` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `value` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `type` ENUM('string', 'bool', 'int', 'float', 'array', 'time', 'json') CHARACTER SET 'utf8' NOT NULL DEFAULT 'string',
  `preferenceable_type` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `preferenceable_id` INT(10) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `preferences_key_preferenceable_type_preferenceable_id_unique` (`key` ASC, `preferenceable_type` ASC, `preferenceable_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `timegrid`.`role_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timegrid`.`role_user` ;

CREATE TABLE IF NOT EXISTS `timegrid`.`role_user` (
  `role_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`, `user_id`),
  INDEX `role_user_user_id_foreign` (`user_id` ASC),
  CONSTRAINT `role_user_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `timegrid`.`roles` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `role_user_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `timegrid`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `altershift`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `altershift`;
INSERT INTO `altershift`.`users` (`id`, `email`, `password`, `name`, `created_at`, `updated_at`, `is_staff`, `profile_pic`, `bio`, `initial_consult`) VALUES (DEFAULT, 'shannonwhite.rmt@gmail.com', '12b6be543b216f5d24857832594ca5f47ef30c80a4acdf64bcb63de69c9fb3b39b8f1769832b61801f219e38a415b675486eea82c861c2f11a02e4278be44ba5', 'Shannon White', NULL, NULL, true, 'assets/img/staff/shannon.jpg', 'Shannon White holds her Bachelor of Musculoskeletal Therapy and Diploma of Remedial Massage with 10 years experience in the health and wellbeing industry. While specializing in sports massage, she has had an extensive clientele list including the Brisbane Broncos, Waitako Cheifs, St George Illawarra Dragons, Queensland Ballet, Queensland Firebirds, Sunwolves, Queensland Reds and the Wallabies. This has created an adaptive capacity to handle whatever ails you!\n\nShannon utilizes a range of techniques such as;\n\n● Cupping\n\n● Joint and Neural Mobilizations\n\n● Dry needling\n\n● Soft Tissue Release', NULL);
INSERT INTO `altershift`.`users` (`id`, `email`, `password`, `name`, `created_at`, `updated_at`, `is_staff`, `profile_pic`, `bio`, `initial_consult`) VALUES (DEFAULT, 'dandy@doingitwithdandy.com.au', '12b6be543b216f5d24857832594ca5f47ef30c80a4acdf64bcb63de69c9fb3b39b8f1769832b61801f219e38a415b675486eea82c861c2f11a02e4278be44ba5', 'Daniel Donaldson', NULL, NULL, true, 'assets/img/staff/daniel.jpg', 'Doing it with Dandy is a personal training service that gives everyone the opportunity to reach their health & fitness goals. We specialise in Fat Loss, Strength Training & Improving your athletic abilities.\n\nDan has personally lost over 70kg and knows how tough it can be. Also a certified Boxing, MetaFit and kettle bell instructor, he has the skills, experience and know how to help you.', NULL);
INSERT INTO `altershift`.`users` (`id`, `email`, `password`, `name`, `created_at`, `updated_at`, `is_staff`, `profile_pic`, `bio`, `initial_consult`) VALUES (DEFAULT, 'courtneywhite1995.cw@gmail.com', '12b6be543b216f5d24857832594ca5f47ef30c80a4acdf64bcb63de69c9fb3b39b8f1769832b61801f219e38a415b675486eea82c861c2f11a02e4278be44ba5', 'Courtney White', NULL, NULL, true, 'assets/img/staff/courtney.jpg', 'Chasing Summer is all about having that \"Summer Body\" all year round. Courtney has a mass of life experience for someone so young. Overcoming weight issues and injuries means she is capable of assisting people of all backgrounds. She isn\'t just a trainer though, she\'s also a Pilates, Boxing, TRX and Kettle Bell instructor who has a keen interesting in helping people reach their goals.', NULL);
INSERT INTO `altershift`.`users` (`id`, `email`, `password`, `name`, `created_at`, `updated_at`, `is_staff`, `profile_pic`, `bio`, `initial_consult`) VALUES (DEFAULT, 'test@gmail.com', '12b6be543b216f5d24857832594ca5f47ef30c80a4acdf64bcb63de69c9fb3b39b8f1769832b61801f219e38a415b675486eea82c861c2f11a02e4278be44ba5', 'test', NULL, NULL, false, NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `altershift`.`services`
-- -----------------------------------------------------
START TRANSACTION;
USE `altershift`;
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Personal Training', 2, 1);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Group PT', 2, 3);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Musculoskeletal Therapy', 1, 1);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Personal Training', 3, 1);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Group PT', 3, 3);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Pilates', 3, 10);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Strength & Conditioning', 3, 10);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Awake & Active Pilates', 1, 10);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, '24 HIT', 2, 10);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Boxing', 2, 10);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Metafit', 2, 10);

COMMIT;


-- -----------------------------------------------------
-- Data for table `altershift`.`services_detail`
-- -----------------------------------------------------
START TRANSACTION;
USE `altershift`;
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 45, 55, 15, 0, 1);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 45, 55, 15, 0, 4);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 30, 10, 0, 0, 11);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 30, 30, 0, 0, 3);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 45, 45, 0, 0, 3);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 60, 75, 0, 0, 3);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 90, 90, 0, 0, 3);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 45, 10, 15, 0, 2);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 45, 10, 15, 0, 5);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 60, 10, 0, 0, 6);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 45, 15, 0, 0, 7);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 60, 10, 0, 0, 8);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 30, 10, 0, 0, 9);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 45, 10, 0, 0, 10);

COMMIT;


-- -----------------------------------------------------
-- Data for table `altershift`.`availability`
-- -----------------------------------------------------
START TRANSACTION;
USE `altershift`;
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '06:00:00', '19:00:00', 1, 1, 2);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '06:00:00', '19:00:00', 2, 1, 2);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '05:00:00', '19:00:00', 3, 1, 2);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '05:00:00', '19:00:00', 4, 1, 2);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '07:00:00', '18:00:00', 5, 1, 2);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '18:00:00', '18:45:00', 3, 10, 2);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '06:00:00', '06:45:00', 5, 10, 2);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '06:00:00', '18:00:00', 1, 3, 1);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '06:00:00', '18:00:00', 2, 3, 1);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '06:00:00', '18:00:00', 3, 3, 1);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '06:00:00', '18:00:00', 4, 3, 1);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '06:00:00', '18:00:00', 5, 3, 1);

COMMIT;

