-- MySQL Script generated by MySQL Workbench
-- Wed 06 Dec 2017 16:21:36 AEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema altershift
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `altershift` ;

-- -----------------------------------------------------
-- Schema altershift
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `altershift` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema timegrid
-- -----------------------------------------------------
USE `altershift` ;

-- -----------------------------------------------------
-- Table `altershift`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altershift`.`users` ;

CREATE TABLE IF NOT EXISTS `altershift`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `is_staff` TINYINT(1) NOT NULL DEFAULT 0,
  `profile_pic` VARCHAR(150) NULL,
  `bio` VARCHAR(900) NULL DEFAULT NULL,
  `initial_consult` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `altershift`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altershift`.`services` ;

CREATE TABLE IF NOT EXISTS `altershift`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `users_id` INT NOT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_services_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_services_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `altershift`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `altershift`.`services_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altershift`.`services_detail` ;

CREATE TABLE IF NOT EXISTS `altershift`.`services_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` INT NULL,
  `price` INT NULL,
  `break` INT NULL DEFAULT 0,
  `initial_consult` TINYINT(1) NULL DEFAULT 0,
  `services_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_services_detail_services1_idx` (`services_id` ASC),
  CONSTRAINT `fk_services_detail_services1`
    FOREIGN KEY (`services_id`)
    REFERENCES `altershift`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `altershift`.`availability`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altershift`.`availability` ;

CREATE TABLE IF NOT EXISTS `altershift`.`availability` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start` TIME NULL,
  `end` TIME NULL,
  `repeat_weekday` INT NULL,
  `services_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_availability_services1_idx` (`services_id` ASC),
  INDEX `fk_availability_services2_idx` (`users_id` ASC),
  CONSTRAINT `fk_availability_services1`
    FOREIGN KEY (`services_id`)
    REFERENCES `altershift`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_availability_services2`
    FOREIGN KEY (`users_id`)
    REFERENCES `altershift`.`services` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `altershift`.`bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altershift`.`bookings` ;

CREATE TABLE IF NOT EXISTS `altershift`.`bookings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start` TIMESTAMP NOT NULL,
  `finish` TIMESTAMP NULL,
  `status` ENUM('R', 'C', 'A', 'S') NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `users_id` INT NOT NULL,
  `services_id` INT NOT NULL,
  `services_detail_id` INT NOT NULL,
  `is_recurring` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Bookings_users1_idx` (`users_id` ASC),
  INDEX `fk_Bookings_services1_idx` (`services_id` ASC),
  INDEX `fk_Bookings_services_detail1_idx` (`services_detail_id` ASC),
  CONSTRAINT `fk_Bookings_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `altershift`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bookings_services1`
    FOREIGN KEY (`services_id`)
    REFERENCES `altershift`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bookings_services_detail1`
    FOREIGN KEY (`services_detail_id`)
    REFERENCES `altershift`.`services_detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `altershift`.`recurring_bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altershift`.`recurring_bookings` ;

CREATE TABLE IF NOT EXISTS `altershift`.`recurring_bookings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` INT NULL,
  `day_of_week` INT NULL,
  `day_of_month` INT NULL,
  `bookings_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `start` TIME NULL,
  `end` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recurring_bookings_bookings1_idx` (`bookings_id` ASC),
  CONSTRAINT `fk_recurring_bookings_bookings1`
    FOREIGN KEY (`bookings_id`)
    REFERENCES `altershift`.`bookings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `altershift`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `altershift`;
INSERT INTO `altershift`.`users` (`id`, `email`, `password`, `name`, `created_at`, `updated_at`, `is_staff`, `profile_pic`, `bio`, `initial_consult`) VALUES (DEFAULT, 'shannonwhite.rmt@gmail.com', '12b6be543b216f5d24857832594ca5f47ef30c80a4acdf64bcb63de69c9fb3b39b8f1769832b61801f219e38a415b675486eea82c861c2f11a02e4278be44ba5', 'Shannon White', NULL, NULL, true, 'assets/img/staff/shannon.jpg', 'Shannon White holds her Bachelor of Musculoskeletal Therapy and Diploma of Remedial Massage with 10 years experience in the health and wellbeing industry. While specializing in sports massage, she has had an extensive clientele list including the Brisbane Broncos, Waitako Cheifs, St George Illawarra Dragons, Queensland Ballet, Queensland Firebirds, Sunwolves, Queensland Reds and the Wallabies. This has created an adaptive capacity to handle whatever ails you!\n\nShannon utilizes a range of techniques such as;\n\n● Cupping\n\n● Joint and Neural Mobilizations\n\n● Dry needling\n\n● Soft Tissue Release', NULL);
INSERT INTO `altershift`.`users` (`id`, `email`, `password`, `name`, `created_at`, `updated_at`, `is_staff`, `profile_pic`, `bio`, `initial_consult`) VALUES (DEFAULT, 'dandy@doingitwithdandy.com.au', '12b6be543b216f5d24857832594ca5f47ef30c80a4acdf64bcb63de69c9fb3b39b8f1769832b61801f219e38a415b675486eea82c861c2f11a02e4278be44ba5', 'Daniel Donaldson', NULL, NULL, true, 'assets/img/staff/daniel.jpg', 'Doing it with Dandy is a personal training service that gives everyone the opportunity to reach their health & fitness goals. We specialise in Fat Loss, Strength Training & Improving your athletic abilities.\n\nDan has personally lost over 70kg and knows how tough it can be. Also a certified Boxing, MetaFit and kettle bell instructor, he has the skills, experience and know how to help you.', NULL);
INSERT INTO `altershift`.`users` (`id`, `email`, `password`, `name`, `created_at`, `updated_at`, `is_staff`, `profile_pic`, `bio`, `initial_consult`) VALUES (DEFAULT, 'courtneywhite1995.cw@gmail.com', '12b6be543b216f5d24857832594ca5f47ef30c80a4acdf64bcb63de69c9fb3b39b8f1769832b61801f219e38a415b675486eea82c861c2f11a02e4278be44ba5', 'Courtney White', NULL, NULL, true, 'assets/img/staff/courtney.jpg', 'Chasing Summer is all about having that \"Summer Body\" all year round. Courtney has a mass of life experience for someone so young. Overcoming weight issues and injuries means she is capable of assisting people of all backgrounds. She isn\'t just a trainer though, she\'s also a Pilates, Boxing, TRX and Kettle Bell instructor who has a keen interesting in helping people reach their goals.', NULL);
INSERT INTO `altershift`.`users` (`id`, `email`, `password`, `name`, `created_at`, `updated_at`, `is_staff`, `profile_pic`, `bio`, `initial_consult`) VALUES (DEFAULT, 'test@gmail.com', '12b6be543b216f5d24857832594ca5f47ef30c80a4acdf64bcb63de69c9fb3b39b8f1769832b61801f219e38a415b675486eea82c861c2f11a02e4278be44ba5', 'test', NULL, NULL, false, NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `altershift`.`services`
-- -----------------------------------------------------
START TRANSACTION;
USE `altershift`;
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Personal Training', 2, 1);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Group PT', 2, 3);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Musculoskeletal Therapy', 1, 1);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Personal Training', 3, 1);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Group PT', 3, 3);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Pilates', 3, 10);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Strength & Conditioning', 3, 10);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Awake & Active Pilates', 1, 10);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, '24 HIT', 2, 10);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Boxing', 2, 10);
INSERT INTO `altershift`.`services` (`id`, `name`, `users_id`, `capacity`) VALUES (DEFAULT, 'Metafit', 2, 10);

COMMIT;


-- -----------------------------------------------------
-- Data for table `altershift`.`services_detail`
-- -----------------------------------------------------
START TRANSACTION;
USE `altershift`;
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 45, 55, 15, 0, 1);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 45, 55, 15, 0, 4);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 30, 10, 0, 0, 11);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 30, 30, 0, 0, 3);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 45, 45, 0, 0, 3);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 60, 75, 0, 0, 3);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 90, 90, 0, 0, 3);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 45, 10, 15, 0, 2);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 45, 10, 15, 0, 5);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 60, 10, 0, 0, 6);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 45, 15, 0, 0, 7);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 60, 10, 0, 0, 8);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 30, 10, 0, 0, 9);
INSERT INTO `altershift`.`services_detail` (`id`, `time`, `price`, `break`, `initial_consult`, `services_id`) VALUES (DEFAULT, 45, 10, 0, 0, 10);

COMMIT;


-- -----------------------------------------------------
-- Data for table `altershift`.`availability`
-- -----------------------------------------------------
START TRANSACTION;
USE `altershift`;
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '06:00:00', '19:00:00', 1, 1, 2);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '06:00:00', '19:00:00', 2, 1, 2);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '05:00:00', '19:00:00', 3, 1, 2);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '05:00:00', '19:00:00', 4, 1, 2);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '07:00:00', '18:00:00', 5, 1, 2);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '18:00:00', '19:00:00', 3, 10, 2);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '06:00:00', '07:00:00', 5, 10, 2);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '06:00:00', '18:00:00', 1, 3, 1);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '06:00:00', '18:00:00', 2, 3, 1);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '06:00:00', '18:00:00', 3, 3, 1);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '06:00:00', '18:00:00', 4, 3, 1);
INSERT INTO `altershift`.`availability` (`id`, `start`, `end`, `repeat_weekday`, `services_id`, `users_id`) VALUES (DEFAULT, '06:00:00', '18:00:00', 5, 3, 1);

COMMIT;

